import random
from base64 import b64decode

from flask import json, url_for

from limits.api.models import Card


def test_generate_token(client):
    """
    The client can fetch a token generated by the server
    """
    url = url_for('api.generate_token')

    response = client.post(url, data={})

    assert response.status_code == 200
    data = json.loads(response.data)
    assert set(data.keys()) == {'client_token'}
    token = data['client_token']
    decoded = json.loads(b64decode(token))
    assert decoded['version'] == 2


def random_amount(maximum, *, minimum=0):
    """
    Generate a random amount of money

    Using random amounts we avoid 'duplicate' errors. We could disable that
    check in the Sandbox settings, but then we couldn't test that specific
    condition.
    """
    return str(round(random.uniform(minimum, maximum), 2))


def test_load_card(client):
    """
    The client can load money into a card

    Note: we use specific 'nonce' and 'amount' test values to trigger different
    responses from the external API
    """
    nonce, amount = 'fake-valid-visa-nonce', random_amount(1999.99)
    card_id = Card.query.one().id
    url = url_for('api.load_card', card_id=card_id)

    response = client.post(url, data={'nonce': nonce, 'amount': amount})

    assert response.status_code == 200
    data = json.loads(response.data)
    assert data == {'status': 'ok', 'errors': []}
